Repository trusttoken/smart-contracts, pull requests merged in 2021-11, with the labels that each got.

#1082 🦦 Deprecate true lender
  contracts/truefi/TrueFiPool.sol
  contracts/truefi2/PoolExtensions.sol
  contracts/truefi2/PoolFactory.sol
  contracts/truefi2/TrueFiPool2.sol
  contracts/truefi2/deprecated/ITrueLender2Deprecated.sol
  contracts/truefi2/deprecated/TrueLender2Deprecated.sol
  contracts/truefi2/interface/ITrueFiPool2.sol
  contracts/truefi2/mocks/TestTrueFiPool2.sol
  contracts/truefi2/mocks/TestTrueLender.sol
  deploy/truefi2.ts
  docs/truefi/TrueFiPool.md
  docs/truefi2/PoolExtensions.md
  docs/truefi2/PoolFactory.md
  docs/truefi2/TrueFiPool2.md
  docs/truefi2/TrueLender2.md
  docs/truefi2/interface/ITrueFiPool2.md
  docs/truefi2/interface/ITrueLender2.md
  docs/truefi2/mocks/TestTrueLender.md
  slither.sh
  test/integration/FixedTermLoanAgency.test.ts
  test/integration/TrueFiPool2.test.ts
  test/integration/curveYearnStrategy.test.ts
  test/truefi/TrueFiPool.test.ts
  test/truefi2/FixedTermLoanAgency.test.ts
  test/truefi2/Liquidator2.test.ts
  test/truefi2/LoanToken2.test.ts
  test/truefi2/PoolFactory.test.ts
  test/truefi2/SAFU.test.ts
  test/truefi2/TrueFiPool2.test.ts
  test/truefi2/TrueLender2Deprecated.test.ts
  test/utils/setupTruefi2.ts
Labels: Merge Me

#1101 ✅ Add minimal BorrowingMutex formal verification
  .gitignore
  spec/truefi2/BorrowingMutex.spec
  spec/truefi2/TrueFiPool2.spec
  spec/truefi2/scripts/BorrowingMutex.sh
  spec/truefi2/scripts/TrueFiPool2.sh
Labels: Merge Me, Formal Verification

#1110 📎 Add more BorrowingMutex specification
  spec/truefi2/BorrowingMutex.spec
Labels: Formal Verification

#1103 🚜 Add minimal RateModel formal verification
  spec/truefi2/RateModel.spec
  spec/truefi2/scripts/RateModel.sh
Labels: Formal Verification

#1112 🪁 Add sanity checks to formal verification
  spec/truefi2/scripts/BorrowingMutex.sh
Labels: Formal Verification

#1120 🥧 Use appropriate address constants
  test/proxy/OwnedProxyWithReference.test.ts
  test/proxy/OwnedUpgradeabilityProxy.test.ts
  test/registry/Registry.test.ts
  test/truefi/distributors/LinearTrueDistributor.test.ts
  test/truefi2/BorrowingMutex.test.ts
  test/truefi2/FixedTermLoan.test.ts
  test/truefi2/lines-of-credit/LineOfCreditAgency.test.ts
  test/utils/constants.ts
Labels: Merge Me

#1121 ↩️ Return unchanged score parameter if stakedAmount is 0
  contracts/truefi2/RateModel.sol
Labels: Merge Me

#1119 ✍️ Change RatingModel.effectiveScore() signature, so pool argument comes first
  contracts/truefi2/FixedTermLoanAgency.sol
  contracts/truefi2/LineOfCreditAgency.sol
  contracts/truefi2/RateModel.sol
  contracts/truefi2/interface/IRateModel.sol
  test/truefi2/lines-of-credit/RateModel.test.ts
Labels: Merge Me

#1118 🔁 Optimise LOCA.borrow() by not iterating through all of the pools when not necessary
  contracts/truefi2/LineOfCreditAgency.sol
  test/truefi2/StakingVault.test.ts
  test/truefi2/lines-of-credit/LineOfCreditAgency.test.ts
Labels: Merge Me

#1117 👺 Prevent malicious borrower from overloading loans array
  contracts/truefi2/FixedTermLoan.sol
  test/truefi2/FixedTermLoan.test.ts
  test/truefi2/FixedTermLoanAgency.test.ts
  test/truefi2/TrueFiPool2.test.ts
Labels: Merge Me

#1130 🃏 Add minimal Fixed Term Loan verification
  spec/truefi2/FixedTermLoan.spec
  spec/truefi2/scripts/FixedTermLoan.sh
Labels: Formal Verification

#1136 ✅ Add Certora to CircleCI
  .circleci/config.yml
  spec/run.sh
Labels: Formal Verification

#1135 🌲 Set up solc and Certora versions in local env
  .circleci/config.yml
  spec/run.sh
Labels: Formal Verification

#1134 🗯 Move methods to rule arguments
  spec/truefi2/BorrowingMutex.spec
  spec/truefi2/scripts/BorrowingMutex.sh
Labels: Formal Verification

#1138 🪃 Check for fallback functions in rules
  spec/truefi2/BorrowingMutex.spec
Labels: Formal Verification
